

### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john@gmail.com",
  "password": "John@1234",
  "role": "USER"
}

###  Register Admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "admin_user",
  "email": "admin@gmail.com",
  "password": "Admin@1234",
  "role": "ADMIN"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "John@1234"
}

### Login Admin
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Admin@1234"
}

### Logout
POST http://localhost:5000/api/auth/logout
Content-Type: application/json